function fn = writeAutopilotParams(P, NM, outdir)
% WRITEAUTOPILOTPARAMS  Emit ArduPilot Rover parameters from the derived design.
%
% ArduPilot Rover's steering path is:
%   heading error -> ATC_STR_ANG_P -> desired turn rate [rad/s]
%                 -> ATC_STR_RAT_{P,I,D,FF} -> NORMALISED steering output -1..1
%
% Two things about that mapping matter here.
%
% 1. The rate controller's output is NORMALISED, not an angle. So the
%    angle-domain gain must be divided by delta_max to become an ATC_STR_RAT_P.
%
% 2. ROVER HAS NO NATIVE GAIN SCHEDULING on the steering rate loop. Its output
%    is a steering angle, so the u^2 rudder authority sits OUTSIDE the loop and
%    is not compensated anywhere. That is exactly the configuration in which the
%    1/U^2 angle-domain schedule is genuinely required. A single fixed
%    ATC_STR_RAT_P can only be correct at one speed.
%
%    Options, in order of preference:
%      (a) run the boat at a roughly constant cruise speed and tune there --
%          simplest, and viable because the course is run at one speed;
%      (b) use Rover's Lua scripting to write ATC_STR_RAT_P from measured speed
%          as P = P_ref * (U_ref/U)^2;
%      (c) accept the degradation. Per the study that is about 3x worse
%          overshoot at the LOW speed end, and it does not go unstable --
%          largely because differential thrust (skid steering) carries the
%          low-speed end. Acceptable if the boat never manoeuvres hard slowly.

if nargin < 3, outdir = fullfile(fileparts(fileparts(mfilename('fullpath'))),'results'); end
if ~exist(outdir,'dir'), mkdir(outdir); end

U_ref = 6.7;                                    % [m/s] 15 mph tuning point
G  = gainSchedule(U_ref, NM, P);
Gs = gainSchedule([2.2 4 6.7 10 13.4], NM, P);

dmax = P.R.delta_max;                            % [rad] full steering deflection
RE   = rollEnvelope(U_ref, P);

% Achievable steady yaw rate at the tuning speed, at the ventilation-limited
% useful deflection. The rate LIMIT should sit just above what the boat can
% actually do -- setting it to the roll envelope (which is 3-6x higher than
% achievable) makes it a dead parameter that never engages.
Tt   = hullSteadyState(U_ref, P).R_total/2;
Sach = simOsprey([U_ref;0;0;0;0;0;Tt;Tt;0], 20, ...
       struct('delta_cmd', min(P.R.delta_vent_on, dmax), ...
              'T_cmd_port', Tt, 'T_cmd_stbd', Tt), P, struct('dt',0.005));
r_ach   = abs(Sach.r(end));                      % [rad/s]
r_limit = min(1.5 * r_ach, RE.r_max_safe);       % [rad/s]

% Angle-domain gain -> normalised (-1..1) steering output.
STR_RAT_P = G.Kp_r / dmax;
STR_RAT_I = G.Ki_r / dmax;
STR_RAT_D = 0;                                   % see summary.md sec.4 note 2
STR_RAT_FF= 1 / (G.K * dmax);                    % steady-state r per unit steer

% L1 guidance: ArduPilot uses L1_dist = U * NAVL1_PERIOD / (pi * NAVL1_DAMPING)
L_a       = 3 * P.V.LOA;                         % [m] lookahead used in the study
NAVL1_DAMPING = 0.75;
NAVL1_PERIOD  = L_a * pi * NAVL1_DAMPING / U_ref;

fn = fullfile(outdir, 'autopilot_params.txt');
f = fopen(fn, 'w');

fprintf(f, '# ArduPilot Rover parameters -- Osprey USV\n');
fprintf(f, '# Generated by analysis/writeAutopilotParams.m\n');
fprintf(f, '# Tuning point: U_ref = %.1f m/s (15 mph)\n', U_ref);
fprintf(f, '#\n');
fprintf(f, '# READ results/summary.md BEFORE FLYING THESE.\n');
fprintf(f, '# Hull derivatives behind these gains are swept +/-5x; the SCALING\n');
fprintf(f, '# is trustworthy, the absolute values are not. Start at 50%% of the\n');
fprintf(f, '# P gains below and increase on the water.\n');
fprintf(f, '#\n');
fprintf(f, '# Nomoto fit: K'' = %.3f, T'' = %.3f (identified on the sim, not the boat)\n', ...
        NM.K_prime, NM.T_prime);
fprintf(f, '# At U_ref: K = %.3f 1/s, T = %.3f s\n', G.K, G.T);
fprintf(f, '#\n\n');

fprintf(f, '# ---- Steering rate controller (inner loop) ----\n');
fprintf(f, 'ATC_STR_RAT_P,%.4f\n',  STR_RAT_P);
fprintf(f, 'ATC_STR_RAT_I,%.4f\n',  STR_RAT_I);
fprintf(f, 'ATC_STR_RAT_D,%.4f\n',  STR_RAT_D);
fprintf(f, 'ATC_STR_RAT_FF,%.4f\n', STR_RAT_FF);
fprintf(f, 'ATC_STR_RAT_FLTT,%.2f\n', G.wc_r/(2*pi)*2);
fprintf(f, 'ATC_STR_RAT_FLTD,%.2f\n', 10.0);
fprintf(f, 'ATC_STR_RAT_MAX,%.1f\n', rad2deg(r_limit));
fprintf(f, '# ATC_STR_RAT_D is ZERO deliberately: heading-derived rate noise\n');
fprintf(f, '# (1.5 deg at 50 Hz = 1.85 rad/s) makes derivative unusable.\n');
fprintf(f, '# ATC_STR_RAT_MAX = 1.5x the ACHIEVABLE rate (%.2f rad/s at %.1f m/s\n', ...
        r_ach, U_ref);
fprintf(f, '# at the %.0f deg ventilation-limited deflection), capped by the roll\n', ...
        rad2deg(min(P.R.delta_vent_on, dmax)));
fprintf(f, '# envelope (%.2f rad/s). The envelope is NOT binding -- the rudder is.\n\n', ...
        RE.r_max_safe);

fprintf(f, '# ---- Heading controller (outer loop) ----\n');
fprintf(f, 'ATC_STR_ANG_P,%.3f\n', G.Kp_psi);
fprintf(f, 'ATC_STR_ACC_MAX,%.1f\n', rad2deg(G.wc_r * min(RE.r_max_safe,1.0)));
fprintf(f, 'ATC_TURN_MAX_G,%.2f\n', 0.6 * RE.a_y_crit / 9.80665);
fprintf(f, '# ATC_TURN_MAX_G derived from sponson unloading at %.2f g with a 0.6 SF.\n\n', ...
        RE.a_y_crit/9.80665);

fprintf(f, '# ---- Navigation / L1 ----\n');
fprintf(f, 'NAVL1_PERIOD,%.2f\n',  NAVL1_PERIOD);
fprintf(f, 'NAVL1_DAMPING,%.2f\n', NAVL1_DAMPING);
fprintf(f, 'WP_RADIUS,%.1f\n',     2 * P.V.LOA);
fprintf(f, 'WP_OVERSHOOT,%.1f\n',  P.V.LOA);
fprintf(f, 'CRUISE_SPEED,%.1f\n',  U_ref);
fprintf(f, '# NAVL1_PERIOD from a %.1f m lookahead (3 x LOA) at U_ref.\n\n', L_a);

fprintf(f, '# ---- Speed / throttle ----\n');
fprintf(f, 'CRUISE_THROTTLE,%.0f\n', 55);
fprintf(f, 'ATC_SPEED_P,%.2f\n', 0.20);
fprintf(f, 'ATC_SPEED_I,%.2f\n', 0.20);
fprintf(f, 'ATC_ACCEL_MAX,%.1f\n', 3.0);
fprintf(f, 'ATC_DECEL_MAX,%.1f\n', 3.0);
fprintf(f, 'MOT_THR_MAX,%.0f\n', 100);
fprintf(f, '\n');

fprintf(f, '# ---- Steering travel ----\n');
fprintf(f, '# IMPORTANT: limit servo travel to VENTILATION ONSET, not the\n');
fprintf(f, '# mechanical stop. Yaw moment PEAKS at %.0f deg and FALLS beyond it\n', ...
        rad2deg(P.R.delta_vent_on));
fprintf(f, '# (64.4 -> 38.7 N*m at 13.4 m/s), latched until the blade unloads\n');
fprintf(f, '# below %.0f deg. Commanding past onset gives the loop a NEGATIVE\n', ...
        rad2deg(P.R.delta_vent_on - P.R.vent_hysteresis));
fprintf(f, '# plant gain and a limit cycle. Set SERVOn_MIN/MAX for +/-%.0f deg,\n', ...
        rad2deg(P.R.delta_vent_on));
fprintf(f, '# NOT the +/-%.0f deg the linkage can reach.\n\n', rad2deg(P.R.delta_max));

fprintf(f, '# ---- Gain schedule (Rover cannot do this natively) ----\n');
fprintf(f, '# ATC_STR_RAT_P must scale as (U_ref/U)^2. Apply via Lua, or accept\n');
fprintf(f, '# ~3x worse overshoot at the low-speed end.\n');
fprintf(f, '#   U [m/s]    ATC_STR_RAT_P    ATC_STR_RAT_I\n');
for i = 1:numel(Gs.U)
    fprintf(f, '#   %6.1f     %12.4f     %12.4f\n', ...
            Gs.U(i), Gs.Kp_r(i)/dmax, Gs.Ki_r(i)/dmax);
end

fclose(f);
end
