"""python -m osprey report — run every study and write results/python/.

Writes report.md (every number the docs quote, in tables), monte_carlo.csv
and the figures. results/summary.md is the human write-up of this file; when
the model changes, regenerate this and update the summary from it.
"""
from __future__ import annotations

import csv
import math
import time
from datetime import date
from pathlib import Path

import numpy as np

from .hull import hull_solve
from .nomoto import gain_schedule, identify_nomoto
from .params import AS_BUILT, DEG, KGCM, PROPOSED, UNCERTAINTY, build_params
from .propulsion import prop_max_thrust
from .race import AUTOPILOT, MPH, Course, controller_params, plot_race, run_race, top_speed
from .rudder import cavitation_speed, rudder_forces
from .sizing import SERVO_SPEEDS_MPH, compare, thesis_servo_check
from .studies import (RACE_WIND, FAULT_T, area_vs_span, failure_modes, jam_moment_balance,
                      mc_summary, monte_carlo, race_params, roll_envelope, rounding_study,
                      turn_budget)


def _table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def _f(x, fmt="{:.2f}"):
    if x is None or (isinstance(x, float) and not math.isfinite(x)):
        return "—"
    return fmt.format(x)


def build_report(out: Path, n_mc=60, workers=None) -> Path:
    out.mkdir(parents=True, exist_ok=True)
    t_start = time.time()
    md = [f"# Osprey — model report\n",
          f"Generated by `python -m osprey report --n {n_mc}` on {date.today()}. "
          "Machine-written: every table below is recomputed from the Python model. "
          "The human write-up with caveats is `../summary.md`.\n",
          "**Race configuration unless stated:** 45 mm × 5 in rudder, 50 mph cruise, "
          "standing start, two marks 0.25 mi apart rounded at 25 m, 2 miles, "
          "propulsion scaled so the loaded boat tops out at 55 mph (assumed upgrade), "
          "controller `controllers/oval_autopilot.lua`.\n"]

    # ---- 1. validation ----------------------------------------------------
    Pl = build_params()
    V, E = Pl.V, Pl.E
    Hd = hull_solve(V.U_demo, V, E, V.m_dry)
    Hdes = hull_solve(V.U_design, V, E, Pl.m)
    sig80 = rudder_forces(0.0, V.U_design, 0, 0, 0, Pl)[3]["sigma"]
    md += ["## 1. Validation anchors\n",
           _table(["check", "reported", "model", "status"], [
               ["aero lift fraction at 35.8 m/s", "36% of weight", f"{100 * Hdes['f_aero']:.1f}%",
                "calibrated to this (not a check)"],
               ["effective power at 13.4 m/s, no payload",
                "~2400 W (45 A × 44.4 V × 2, ~60% chain)", f"{Hd['R_total'] * V.U_demo:.0f} W",
                "independent (MATLAB's 2534 W used the loaded mass)"],
               ["rudder cavitation number at 35.8 m/s", "≈ 0.15", f"{sig80:.3f}", "independent"],
           ]), ""]

    # ---- 2. rudder comparison and servo -----------------------------------
    P0 = build_params()
    C = compare(P0, (AS_BUILT, PROPOSED))
    md += ["## 2. Rudder comparison\n",
           _table(["", *[c["name"] for c in C]], [
               ["submerged span [mm]", *[f"{c['span_mm']:.0f}" for c in C]],
               ["chord [mm]", *[f"{c['chord_mm']:.0f}" for c in C]],
               ["wetted area [in²]", *[f"{c['area_in2']:.2f}" for c in C]],
               ["aspect ratio", *[f"{c['AR']:.2f}" for c in C]],
               ["CL_α [1/rad]", *[f"{c['CL_alpha']:.3f}" for c in C]],
               ["authority A·CL_α", *[f"{c['authority']:.2f}×" for c in C]],
               ["turn radius, 10°, 5 m/s [LOA]", *[f"{c['R5_LOA']:.2f}" for c in C]],
               ["turn radius, 10°, 10 m/s [LOA]", *[f"{c['R10_LOA']:.2f}" for c in C]],
               ["90° turn at 5 m/s [s]", *[f"{c['t90_5']:.2f}" for c in C]],
               ["rudder drag, 10°, 10 m/s [% hull]", *[f"{c['drag_pct_10']:.1f}" for c in C]],
               ["cavitation ceiling [mph]", *[f"{c['cav_mps'] / MPH:.1f}" for c in C]],
           ]), ""]
    for key, title in (("servo_clamped", "travel clamped at ventilation onset (autopilot)"),
                       ("servo_full", "full mechanical travel (manual / RC)")):
        md += [f"**Peak servo torque [kg·cm], {title}.** Stock at LE / 0.15c / 0.25c. "
               "0.15c is also a 0.25c stock with the centre of pressure 0.10c off nominal. "
               "Stall 74.\n",
               _table(["speed", *[c["name"] for c in C]],
                      [[f"{mph} mph", *[" / ".join(f"{v:.0f}" for v in c[key][i][1:]) for c in C]]
                       for i, mph in enumerate(SERVO_SPEEDS_MPH)]), ""]
    t = thesis_servo_check(P0)
    md += [f"**Thesis servo sizing, 80 mph:** {t['thesis_kgcm']:.1f} kg·cm (drag × horn radius). "
           "Correct hinge moment for the thesis blade (75 mm submerged):\n",
           _table(["stock", "clamped at onset", "full travel", "peak at", "MATLAB's 35° point"],
                  [[k, f"{t[k]['clamped_kgcm']:.1f}", f"{t[k]['full_kgcm']:.1f}",
                    f"{t[k]['at_deg']:.0f}°", f"{t[k]['matlab_35deg_kgcm']:.1f}"]
                   for k in ("LE", "0.15c", "balanced")]), ""]

    # ---- 3. span vs area --------------------------------------------------
    rows = area_vs_span(P0)
    md += ["## 3. Span, not area\n",
           "Open-loop turn at 10° (the useful limit), 10 m/s.\n",
           _table(["blade", "span [mm]", "chord [mm]", "area", "AR", "CL_α", "authority",
                   "turn radius [LOA]"],
                  [[r["name"], f"{r['span_mm']:.0f}", f"{r['chord_mm']:.0f}", f"{r['area_x']:.1f}×",
                    f"{r['AR']:.2f}", f"{r['CL_alpha']:.2f}", f"{r['authority_x']:.2f}×",
                    f"{r['R_LOA']:.2f}"] for r in rows]), ""]

    # ---- 4. Nomoto and gains ----------------------------------------------
    md += ["## 4. Nomoto fit and gain schedule\n"]
    for rd in (PROPOSED, AS_BUILT):
        Pr = build_params(rudder=rd)
        fit = identify_nomoto(Pr)
        md += [f"**{rd.name}:** K′ = {fit.K_prime:.3f} (spread {100 * fit.K_spread:.0f}%), "
               f"T′ = {fit.T_prime:.3f} (spread {100 * fit.T_spread:.0f}%), "
               f"K ∝ U and T ∝ 1/U scaling holds: {fit.scaling_holds}.\n",
               _table(["U [m/s]", "K [1/s]", "T [s]", "Kp_r (angle)", "Ki_r", "Kp_ψ"],
                      [[U, f"{g['K']:.3f}", f"{g['T']:.3f}", f"{g['Kp_r']:.4f}",
                        f"{g['Ki_r']:.4f}", f"{g['Kp_psi']:.3f}"]
                       for U in (3, 5, 10, 15, 22.35) for g in [gain_schedule(U, fit, Pr)]]), ""]
    Pn = race_params()
    prm = controller_params(Pn, 50 * MPH)
    kp_n = prm["OSP_WC_RATE"] * prm["OSP_NOMOTO_T"] * prm["OSP_LOA"] ** 2 * prm["OSP_RUD_KN"] / prm["OSP_NOMOTO_K"]
    md += [f"The Lua autopilot's yaw-rate loop works in moment units: Kp_N = "
           f"{kp_n:.1f} N·m per rad/s at every speed, for either actuator.\n"]

    # ---- 5. the race ------------------------------------------------------
    md += ["## 5. The race at 50 mph\n"]
    race_rows, keep = [], {}
    for rd in (PROPOSED, AS_BUILT):
        for label, env in (("calm", dict(wind_kt=0, wind_from=90, current=0, current_to=180)),
                           ("15 kt wind + 0.5 m/s current", RACE_WIND)):
            P = race_params(rd, **env)
            res = run_race(P, params=controller_params(race_params(rd), 50 * MPH), tmax=400)
            m = res.metrics
            keep[(rd.name, label)] = (res, P)
            race_rows.append([rd.name, label, "yes" if res.finished else "**no**",
                              _f(m["t_finish"], "{:.1f} s"), _f(m["avg_mph"], "{:.1f}"),
                              f"{m['straight_max']:.2f}", f"{m['xt_max']:.1f}",
                              f"{m['mark_min']:.0f} / {m['mark_max']:.0f}", f"{m['lat_g']:.2f}",
                              f"{m['rudder_peak_deg']:.1f}°", f"{100 * m['clamp_frac']:.1f}%",
                              f"{m['servo_cop_offset_kgcm']:.1f}",
                              "  ".join(f"{v:.1f}" for v in m["lap_rms"])])
    md += [_table(["rudder", "conditions", "finished", "time", "avg mph", "straight max [m]",
                   "max off line [m]", "mark closest / widest [m]", "peak lat g",
                   "peak rudder", "at clamp", "servo, CoP off [kg·cm]", "lap RMS [m]"], race_rows), ""]
    res, P = keep[(PROPOSED.name, "calm")]
    m = res.metrics
    plot_race(res, P, out / "race_50mph.png")
    md += [f"Steering split, proposed rudder, calm: motors {m['t_motor_steer']:.1f} s (below "
           f"10 mph, at launch), rudder {m['t_rudder_steer']:.1f} s, both at once "
           f"{m['ticks_both']} ticks. Figure: `race_50mph.png`.\n"]

    # the prop as logged cannot do 50 mph
    Pg = build_params(rudder=PROPOSED)
    rg = run_race(Pg, params=controller_params(Pg, 50 * MPH), tmax=500)
    md += [f"**Prop as logged (no upgrade):** loaded top speed {top_speed(Pg) / MPH:.1f} mph; "
           f"commanded 50 mph, the race averages {_f(rg.metrics['avg_mph'], '{:.1f}')} mph "
           f"({_f(rg.metrics['t_finish'], '{:.0f}')} s).\n"]

    # ---- 6. rounding radius -----------------------------------------------
    rr = rounding_study()
    md += ["## 6. Rounding radius at 50 mph (calm, proposed rudder)\n",
           _table(["radius [m]", "finished", "time [s]", "avg mph", "closest to mark [m]",
                   "widest [m]", "swings wide by [m]", "peak lat g", "straight max [m]"],
                  [[r["radius"], "yes" if r["finished"] else "no", _f(r["t_finish"], "{:.1f}"),
                    _f(r["avg_mph"], "{:.1f}"), f"{r['mark_min']:.1f}", f"{r['mark_max']:.1f}",
                    f"{r['wide']:.1f}", f"{r['lat_g']:.2f}", f"{r['straight_max']:.2f}"]
                   for r in rr]), ""]

    # ---- 7. Monte Carlo ---------------------------------------------------
    t0 = time.time()
    runs = monte_carlo(n=n_mc, workers=workers)
    t_mc = time.time() - t0
    S = mc_summary(runs)
    with open(out / "monte_carlo.csv", "w", newline="") as f:
        keys = ["rudder", "i", "passed", "lost", "timed_out", "t_finish", "straight_max", "straight_rms",
                "xt_max", "rounding_wide", "mark_min", "lat_g", "clamp_frac", "vent_events",
                "servo_cop_offset_kgcm"]
        w = csv.writer(f)
        w.writerow(keys + list(UNCERTAINTY))
        for r in runs:
            w.writerow([r.get(k) for k in keys] + [r["draw"][k] for k in UNCERTAINTY])
    md += [f"## 7. Monte Carlo — {n_mc} Latin-hypercube draws per rudder\n",
           f"Same draws for both rudders, all {len(UNCERTAINTY)} declared uncertainties, "
           "controller fixed at "
           "the nominal design, 15 kt crosswind + 0.5 m/s current, full race. "
           "**Pass** = finished, never lost, middle-of-straight error ≤ 5 m, never within "
           "5 m of a mark. **Lost** = left the course by more than 150 m or diverged. "
           "**Timed out** = still on the course at three times the race time at cruise. "
           f"({t_mc:.0f} s wall.) Per-draw data: `monte_carlo.csv`.\n",
           _table(["rudder", "pass", "lost", "timed out", "median straight max [m]",
                   "p90 straight max [m]", "median swing-wide [m]", "median lat g",
                   "median at clamp", "p90 at clamp", "ventilated at all", "p90 servo, CoP off",
                   "median time [s]"],
                  [[k, f"{100 * s['passed']:.0f}%", f"{100 * s['lost']:.0f}%",
                    f"{100 * s['timed_out']:.0f}%",
                    _f(s.get("straight_max_med")), _f(s.get("straight_max_p90")),
                    _f(s.get("wide_med"), "{:.1f}"), _f(s.get("lat_g_med")),
                    _f(100 * s.get("clamp_med", float("nan")), "{:.1f}%"),
                    _f(100 * s.get("clamp_p90", float("nan")), "{:.1f}%"),
                    _f(100 * s.get("vent_any", float("nan")), "{:.0f}%"),
                    _f(s.get("servo_p90"), "{:.1f}"), _f(s.get("time_med"), "{:.1f}")]
                   for k, s in S.items()]), ""]
    for k, s in S.items():
        if s.get("rho_xt"):
            top = list(s["rho_xt"].items())[:6]
            md += [f"Spearman ρ with max distance off the line, **{k}**: " +
                   ", ".join(f"{p} {v:+.2f}" for p, v in top) + "\n"]
    lost_draws = {k: [r for r in runs if r["rudder"] == k and r.get("lost")] for k in S}
    for k, L in lost_draws.items():
        if L:
            md += [f"Lost draws, **{k}** (n = {len(L)}), median vs all draws: " +
                   ", ".join(f"{p} {np.median([r['draw'][p] for r in L]):.2f} vs "
                             f"{np.median([r['draw'][p] for r in runs if r['rudder'] == k]):.2f}"
                             for p in ("Nr_fac", "Nv_fac", "Yv_fac", "CLa_fac", "Iz_fac")) + "\n"]
    _plot_mc(runs, out / "monte_carlo.png")

    # does robustness depend on cruise speed? same draws, same boat, proposed rudder
    sweep = []
    for mph in (20, 30, 40):
        Rs = monte_carlo(n=n_mc, rudders=(PROPOSED,), cruise_mph=mph, workers=workers)
        s = mc_summary(Rs)[PROPOSED.name]
        sweep.append((mph, s))
    sweep.append((50, S[PROPOSED.name]))
    md += ["**Same draws, proposed rudder, by cruise speed** (same boat and propulsion; "
           "only the commanded speed changes):\n",
           _table(["cruise [mph]", "pass", "lost", "timed out", "median straight max [m]",
                   "median swing-wide [m]", "median time [s]"],
                  [[mph, f"{100 * s['passed']:.0f}%", f"{100 * s['lost']:.0f}%",
                    f"{100 * s['timed_out']:.0f}%",
                    _f(s.get("straight_max_med")), _f(s.get("wide_med"), "{:.1f}"),
                    _f(s.get("time_med"), "{:.1f}")] for mph, s in sweep]), ""]

    # ---- 8. failure modes -------------------------------------------------
    fm = failure_modes()
    md += [f"## 8. Failure modes (proposed rudder, 15 kt + current, fault at {FAULT_T:.0f} s, "
           "mid first straight at 50 mph)\n",
           _table(["fault", "finished", "lost", "disarmed", "heading change in 5 s",
                   "peak yaw rate [°/s]", "peak lat g", "max off line [m]"],
                  [[r["name"], "yes" if r["finished"] else "no", "yes" if r["lost"] else "no",
                    _f(None if r["finished"] else r["disarm_t"], "{:.1f} s"),
                    f"{r['heading_change_5s']:.0f}°",
                    f"{r['yaw_rate_peak']:.0f}", f"{r['lat_g']:.2f}", f"{r['xt_max']:.0f}"]
                   for r in fm]), ""]
    _plot_faults(fm, out / "failure_modes.png")
    jb = jam_moment_balance(race_params())
    md += ["**Rudder jammed at 10° vs the most the motors can do** (one full, one idle):\n",
           _table(["speed [mph]", "jammed rudder [N·m]", "motors [N·m]", "margin [N·m]"],
                  [[r["mph"], f"{r['N_jam']:.0f}", f"{r['N_thrust']:.0f}", f"{r['margin']:+.0f}"]
                   for r in jb]), ""]

    # ---- 9. turn physics and roll envelope --------------------------------
    tb = turn_budget(race_params())
    md += ["## 9. Open-loop turn at 10° from straight running (proposed rudder)\n",
           _table(["speed [mph]", "speed lost", "peak lat g", "radius [m]",
                   "Munk / rudder moment", "sideslip [°]", "cavitation σ"],
                  [[r["mph"], f"{r['speed_loss_pct']:.0f}%", f"{r['lat_g']:.2f}",
                    f"{r['radius_m']:.1f}", f"{r['munk_over_rudder']:.2f}",
                    f"{r['beta_deg']:.1f}", f"{r['sigma']:.2f}"] for r in tb]), ""]
    Pp = race_params()
    rows = []
    for label, xu, yv in (("surge added mass high, sway low", UNCERTAINTY["Xudot_frac"].hi,
                           UNCERTAINTY["Yvdot_frac"].lo),
                          ("nominal", UNCERTAINTY["Xudot_frac"].nom, UNCERTAINTY["Yvdot_frac"].nom),
                          ("surge low, sway high", UNCERTAINTY["Xudot_frac"].lo,
                           UNCERTAINTY["Yvdot_frac"].hi)):
        for mph in (30, 50):
            u = mph * MPH
            v = u * math.tan(5 * DEG)
            n_munk = (-xu * Pp.m + yv * Pp.m) * u * v
            n_rud = abs(rudder_forces(Pp.R.delta_vent_on, u, 0, 0, 0, Pp)[2])
            rows.append([label, mph, f"{n_munk:+.0f}", f"{n_rud:.0f}", f"{100 * abs(n_munk) / n_rud:.0f}%"])
    md += ["**Munk moment at 5° sideslip vs full useful rudder (10°), proposed rudder:**\n",
           _table(["added-mass case", "speed [mph]", "Munk [N·m]", "rudder [N·m]", "Munk / rudder"],
                  rows), ""]
    md += ["**Roll / hooking envelope** (quasi-static; the 3-DOF model cannot see roll):\n",
           _table(["speed [mph]", "sponson unloads at", "safe yaw rate [rad/s]",
                   "= lateral g", "binding", "aero lift fraction"],
                  [[mph, f"{e['a_y_crit_g']:.2f} g", f"{e['r_safe']:.3f}",
                    f"{e['r_safe'] * e['u'] / 9.80665:.2f}", e["binding"], f"{e['f_aero']:.2f}"]
                   for mph in (10, 20, 30, 40, 50) for e in [roll_envelope(mph * MPH, Pp)]]), ""]

    # ---- 10. powertrain ---------------------------------------------------
    rows = []
    for mph in (30, 40, 50, 55, 80):
        u = mph * MPH
        R = Pl.HT.lookup(u)[1]
        rows.append([mph, f"{R:.0f}", f"{R * u / 1e3:.1f}", f"{2 * prop_max_thrust(u, Pl):.0f}",
                     f"{2 * prop_max_thrust(u, Pp):.0f}"])
    md += ["## 10. Powertrain\n",
           _table(["speed [mph]", "hull resistance, loaded [N]", "power into water [kW]",
                   "thrust available, prop as logged [N]", "thrust available, sized for 55 mph [N]"],
                  rows), "",
           f"Loaded top speed with the prop as logged: {top_speed(Pl) / MPH:.1f} mph. "
           f"Zero-speed resistance (model defect, PORTING.md): {Pl.HT.lookup(0.0)[1]:.0f} N.\n"]

    md += [f"\n_Report built in {time.time() - t_start:.0f} s._\n"]
    path = out / "report.md"
    path.write_text("\n".join(md), encoding="utf-8")
    return path


def _plot_mc(runs, path):
    """runs: dicts with rudder, lost, timed_out, xt_max, straight_max, draw{...}."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.ticker import FixedLocator, NullFormatter, NullLocator
    fig, ax = plt.subplots(1, 2, figsize=(12, 4.5), constrained_layout=True)
    for j, name in enumerate(dict.fromkeys(r["rudder"] for r in runs)):
        R = [r for r in runs if r["rudder"] == name]
        ok = [r for r in R if not r.get("lost") and not r.get("timed_out")]
        spun = [r for r in R if r.get("timed_out")]
        bad = [r for r in R if r.get("lost")]
        c = f"C{j}"
        ax[0].scatter([r["draw"]["Nr_fac"] for r in ok], [r["xt_max"] for r in ok], s=14, c=c,
                      label=f"{name}: finished")
        ax[0].scatter([r["draw"]["Nr_fac"] for r in bad], [150] * len(bad), s=30, c=c, marker="x",
                      label=f"{name}: lost")
        ax[0].scatter([r["draw"]["Nr_fac"] for r in spun], [-8 - 4 * j] * len(spun), s=30, c=c,
                      marker="v", label=f"{name}: spun at launch")
        ax[1].scatter([r["draw"]["CLa_fac"] for r in ok], [r["straight_max"] for r in ok], s=14, c=c,
                      label=name)
    ax[0].set_xscale("log")
    ax[0].xaxis.set_major_locator(FixedLocator([0.2, 0.5, 1, 2, 5]))
    ax[0].xaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter("%g"))
    ax[0].xaxis.set_minor_locator(NullLocator()); ax[0].xaxis.set_minor_formatter(NullFormatter())
    ax[0].set(xlabel="yaw damping factor Nr_fac", ylabel="max off line [m]",
              title="50 mph race: x = lost (at 150 m), v = spun at launch")
    ax[1].set(xlabel="rudder lift factor CLa_fac", ylabel="middle-of-straight max [m]",
              title="straight-line tracking, finished boats")
    ax[1].axhline(5, color="0.5", ls=":")
    for a in ax:
        a.grid(alpha=0.3); a.legend(loc="best", fontsize=7)
    fig.savefig(path, dpi=110)
    plt.close(fig)


def plot_mc_csv(csv_path, path):
    """Redraw the Monte Carlo figure from monte_carlo.csv without re-running."""
    rows = []
    for r in csv.DictReader(open(csv_path, encoding="utf-8")):
        num = lambda k: float(r[k]) if r[k] not in ("", "None") else float("nan")
        rows.append(dict(rudder=r["rudder"], lost=r["lost"] == "True",
                         timed_out=r["timed_out"] == "True", xt_max=num("xt_max"),
                         straight_max=num("straight_max"),
                         draw={k: float(r[k]) for k in UNCERTAINTY}))
    _plot_mc(rows, path)


def _plot_faults(rows, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(1, 1, figsize=(7, 8), constrained_layout=True)
    wn, we = zip(*rows[0]["res"].wpts)
    ax.plot(we, wn, "--", color="0.6", lw=1, label="course")
    for j, r in enumerate(rows):
        S = r["res"].S
        k = S.t <= FAULT_T + 25
        ax.plot(S.Y[k], S.X[k], lw=1.1, color=f"C{j}", label=r["name"])
    ax.set(xlabel="east [m]", ylabel="north [m]",
           title=f"first 25 s after each fault (injected at {FAULT_T:.0f} s)")
    ax.axis("equal"); ax.grid(alpha=0.3); ax.legend(loc="best", fontsize=8)
    fig.savefig(path, dpi=110)
    plt.close(fig)
